<div id="header-container" class="hidden">
	
</div>
<div id="integral-explain-detail-view" class="basic-view">
	<div id="integral-explain-detail-form">
		<h3 class="integral-explain-detail-title">获取方式</h3>
		<table>
			<thead>
				<tr>
					<th>操作</th>
					<th>积分值</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>首次登陆</td>
					<td>+10</td>
				</tr>
				<tr>
					<td>每日首次打开APP</td>
					<td>+10</td>
				</tr>
				<tr>
					<td>成功认领一个小区</td>
					<td>+30</td>
				</tr>
				<tr>
					<td>成功创建一个无记录小区</td>
					<td>+50</td>
				</tr>
				<tr>
					<td>成功添加一个房号</td>
					<td>+5</td>
				</tr>
				<tr>
					<td>删除一个认领小区</td>
					<td>-30</td>
				</tr>
				<tr>
					<td>删除一个创建小区</td>
					<td>50</td>
				</tr>
				<tr>
					<td>删除一个房号</td>
					<td>-5</td>
				</tr>
			</tbody>
		</table>
		<h3 class="integral-explain-detail-title">龙榜积分奖励(每月统计)</h3>
		<table>
			<thead>
				<tr>
					<th>排名</th>
					<th>奖励积分</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>+20000</td>
				</tr>
				<tr>
					<td>2</td>
					<td>+19000</td>
				</tr>
				<tr>
					<td>3</td>
					<td>+18500</td>
				</tr>
				<tr>
					<td>4</td>
					<td>+18000</td>
				</tr>
				<tr>
					<td>5</td>
					<td>+17500</td>
				</tr>
				<tr>
					<td>6</td>
					<td>+17000</td>
				</tr>
				<tr>
					<td>7</td>
					<td>+16500</td>
				</tr>
				<tr>
					<td>8</td>
					<td>+16000</td>
				</tr>
				<tr>
					<td>9</td>
					<td>+15500</td>
				</tr>
				<tr>
					<td>10</td>
					<td>+15000</td>
				</tr>
				<tr>
					<td>11</td>
					<td>+14500</td>
				</tr>
				<tr>
					<td>12</td>
					<td>14000</td>
				</tr>
				<tr>
					<td>13</td>
					<td>+13500</td>
				</tr>
				<tr>
					<td>14</td>
					<td>+13000</td>
				</tr>
				<tr>
					<td>15</td>
					<td>+12500</td>
				</tr>
				<tr>
					<td>16</td>
					<td>+12000</td>
				</tr>
				<tr>
					<td>17</td>
					<td>+11500</td>
				</tr>
				<tr>
					<td>18</td>
					<td>+11000</td>
				</tr>
				<tr>
					<td>19</td>
					<td>+10500</td>
				</tr>
				<tr>
					<td>20</td>
					<td>+10000</td>
				</tr>
				<tr>
					<td>20名以后</td>
					<td>0</td>
				</tr>
			</tbody>
		</table>
		<h3 class="integral-explain-detail-title">所有积分规则解释权归龙眼项目组所有</h3>
	</div>
</div>
