<div id="header-container" class="hidden">
	
</div>
<div id="integral-explain-detail-view" class="basic-view">
	<div id="integral-explain-detail-form">
		<h3 class="integral-explain-detail-title">获取方式</h3>
		<table>
			<thead>
				<tr>
					<th>操作</th>
					<th>积分值</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>首次打开APP</td>
					<td>5分</td>
				</tr>
				<tr>
					<td>创建小区（认领小区）</td>
					<td>10分</td>
				</tr>
				<tr>
					<td>“抢”未分配小区成功</td>
					<td>10分</td>
				</tr>
				<tr>
					<td>小区负责人更换</td>
					<td>-10分</td>
				</tr>
				<tr>
					<td>完善有负责人小区信息</br>审核通过</td>
					<td>10分</td>
				</tr>
				<tr>
					<td>完善无负责人小区</td>
					<td>10分</td>
				</tr>
				<tr>
					<td>小区分配成功</td>
					<td>20分</td>
				</tr>
				<tr>
					<td>“抢”已分配小区成功</td>
					<td>0分</td>
				</tr>
			</tbody>
		</table>
		<h3 class="integral-explain-detail-title">龙榜积分奖励(每月统计全国)</h3>
		<table>
			<thead>
				<tr>
					<th>排名</th>
					<th>奖励积分</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>第1名奖励</td>
					<td>100000分</td>
				</tr>
				<tr>
					<td>第2名奖励</td>
					<td>95000分</td>
				</tr>
				<tr>
					<td>第3名奖励</td>
					<td>90000分</td>
				</tr>
				<tr>
					<td>第4名奖励</td>
					<td>85000分</td>
				</tr>
				<tr>
					<td>第5名奖励</td>
					<td>80000分</td>
				</tr>
				<tr>
					<td>第6名奖励</td>
					<td>75000分</td>
				</tr>
				<tr>
					<td>第7名奖励</td>
					<td>70000分</td>
				</tr>
				<tr>
					<td>第8名奖励</td>
					<td>75000分</td>
				</tr>
				<tr>
					<td>第9名奖励</td>
					<td>60000分</td>
				</tr>
				<tr>
					<td>第10名奖励</td>
					<td>55000分</td>
				</tr>
				
			</tbody>
		</table>
		<h3 class="integral-explain-detail-title">所有积分规则解释权归龙眼项目组所有</h3>
	</div>
</div>
