package com.lanchui.commonBiz.bean.lg;

import java.util.Date;

public class ShopInfo {

    private Integer id;

    private String shopNumber;

    private Integer marketId;

    private Integer marketIdUuid;

    private String marketName;

    private Integer companyId;

    private Integer dealerId;

    private Integer brandId;

    private String brandName;

    private Integer seriesId;

    private String seriesName;

    private Integer isDel;

    private Date createDate;

    private Integer status;

    private String marketBoothNumber;

    private String marketFloor;

    private String shopTel;

    private Date salesStartTime;

    private Date salesEndTime;

    private String shopName;

    private String shopIntroduction;

    private String supplierInfo;


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.id
     *
     * @param id the value for oms_shop_info.id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.shop_number
     *
     * @return the value of oms_shop_info.shop_number
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getShopNumber() {
        return shopNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.shop_number
     *
     * @param shopNumber the value for oms_shop_info.shop_number
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setShopNumber(String shopNumber) {
        this.shopNumber = shopNumber == null ? null : shopNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.market_id
     *
     * @return the value of oms_shop_info.market_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getMarketId() {
        return marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.market_id
     *
     * @param marketId the value for oms_shop_info.market_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setMarketId(Integer marketId) {
        this.marketId = marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.market_id_uuid
     *
     * @return the value of oms_shop_info.market_id_uuid
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getMarketIdUuid() {
        return marketIdUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.market_id_uuid
     *
     * @param marketIdUuid the value for oms_shop_info.market_id_uuid
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setMarketIdUuid(Integer marketIdUuid) {
        this.marketIdUuid = marketIdUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.market_name
     *
     * @return the value of oms_shop_info.market_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getMarketName() {
        return marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.market_name
     *
     * @param marketName the value for oms_shop_info.market_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName == null ? null : marketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.company_id
     *
     * @return the value of oms_shop_info.company_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.company_id
     *
     * @param companyId the value for oms_shop_info.company_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.dealer_id
     *
     * @return the value of oms_shop_info.dealer_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.dealer_id
     *
     * @param dealerId the value for oms_shop_info.dealer_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.brand_id
     *
     * @return the value of oms_shop_info.brand_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.brand_id
     *
     * @param brandId the value for oms_shop_info.brand_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.brand_name
     *
     * @return the value of oms_shop_info.brand_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.brand_name
     *
     * @param brandName the value for oms_shop_info.brand_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.series_id
     *
     * @return the value of oms_shop_info.series_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.series_id
     *
     * @param seriesId the value for oms_shop_info.series_id
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.series_name
     *
     * @return the value of oms_shop_info.series_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.series_name
     *
     * @param seriesName the value for oms_shop_info.series_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName == null ? null : seriesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.is_del
     *
     * @return the value of oms_shop_info.is_del
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.is_del
     *
     * @param isDel the value for oms_shop_info.is_del
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.create_date
     *
     * @return the value of oms_shop_info.create_date
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.create_date
     *
     * @param createDate the value for oms_shop_info.create_date
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.status
     *
     * @return the value of oms_shop_info.status
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.status
     *
     * @param status the value for oms_shop_info.status
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.market_booth_number
     *
     * @return the value of oms_shop_info.market_booth_number
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getMarketBoothNumber() {
        return marketBoothNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.market_booth_number
     *
     * @param marketBoothNumber the value for oms_shop_info.market_booth_number
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setMarketBoothNumber(String marketBoothNumber) {
        this.marketBoothNumber = marketBoothNumber == null ? null : marketBoothNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.market_floor
     *
     * @return the value of oms_shop_info.market_floor
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getMarketFloor() {
        return marketFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.market_floor
     *
     * @param marketFloor the value for oms_shop_info.market_floor
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setMarketFloor(String marketFloor) {
        this.marketFloor = marketFloor == null ? null : marketFloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.shop_tel
     *
     * @return the value of oms_shop_info.shop_tel
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getShopTel() {
        return shopTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.shop_tel
     *
     * @param shopTel the value for oms_shop_info.shop_tel
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setShopTel(String shopTel) {
        this.shopTel = shopTel == null ? null : shopTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.sales_start_time
     *
     * @return the value of oms_shop_info.sales_start_time
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Date getSalesStartTime() {
        return salesStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.sales_start_time
     *
     * @param salesStartTime the value for oms_shop_info.sales_start_time
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setSalesStartTime(Date salesStartTime) {
        this.salesStartTime = salesStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.sales_end_time
     *
     * @return the value of oms_shop_info.sales_end_time
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public Date getSalesEndTime() {
        return salesEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.sales_end_time
     *
     * @param salesEndTime the value for oms_shop_info.sales_end_time
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setSalesEndTime(Date salesEndTime) {
        this.salesEndTime = salesEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.shop_name
     *
     * @return the value of oms_shop_info.shop_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.shop_name
     *
     * @param shopName the value for oms_shop_info.shop_name
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.shop_introduction
     *
     * @return the value of oms_shop_info.shop_introduction
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getShopIntroduction() {
        return shopIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.shop_introduction
     *
     * @param shopIntroduction the value for oms_shop_info.shop_introduction
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setShopIntroduction(String shopIntroduction) {
        this.shopIntroduction = shopIntroduction == null ? null : shopIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_shop_info.supplier_info
     *
     * @return the value of oms_shop_info.supplier_info
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public String getSupplierInfo() {
        return supplierInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_shop_info.supplier_info
     *
     * @param supplierInfo the value for oms_shop_info.supplier_info
     *
     * @mbggenerated Wed Jul 06 13:39:15 CST 2016
     */
    public void setSupplierInfo(String supplierInfo) {
        this.supplierInfo = supplierInfo == null ? null : supplierInfo.trim();
    }
}