package com.lanchui.commonBiz.bean;

import com.xiwa.base.bean.Identified;

import java.util.Date;

public class RedstarStoreFavorite implements Identified {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiwa_redstar_store_favorite.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiwa_redstar_store_favorite.storeId
     *
     * @mbggenerated
     */
    private int storeId;//    店铺Id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiwa_redstar_store_favorite.storeName
     *
     * @mbggenerated
     */
    private String storeName;//  店铺名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiwa_redstar_store_favorite.brandLogo
     *
     * @mbggenerated
     */
    private String brandLogo;//   品牌Logo

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiwa_redstar_store_favorite.createDate
     *
     * @mbggenerated
     */
    private Date createDate;//   创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiwa_redstar_store_favorite.userId
     *
     * @mbggenerated
     */
    private String userId;  //用户ID

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store_favorite.id
     *
     * @return the value of xiwa_redstar_store_favorite.id
     *
     * @mbggenerated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store_favorite.id
     *
     * @param id the value for xiwa_redstar_store_favorite.id
     *
     * @mbggenerated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store_favorite.storeId
     *
     * @return the value of xiwa_redstar_store_favorite.storeId
     *
     * @mbggenerated
     */
    public int getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store_favorite.storeId
     *
     * @param storeId the value for xiwa_redstar_store_favorite.storeId
     *
     * @mbggenerated
     */
    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store_favorite.storeName
     *
     * @return the value of xiwa_redstar_store_favorite.storeName
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store_favorite.storeName
     *
     * @param storeName the value for xiwa_redstar_store_favorite.storeName
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store_favorite.brandLogo
     *
     * @return the value of xiwa_redstar_store_favorite.brandLogo
     *
     * @mbggenerated
     */
    public String getBrandLogo() {
        return brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store_favorite.brandLogo
     *
     * @param brandLogo the value for xiwa_redstar_store_favorite.brandLogo
     *
     * @mbggenerated
     */
    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo == null ? null : brandLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store_favorite.createDate
     *
     * @return the value of xiwa_redstar_store_favorite.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store_favorite.createDate
     *
     * @param createDate the value for xiwa_redstar_store_favorite.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store_favorite.userId
     *
     * @return the value of xiwa_redstar_store_favorite.userId
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store_favorite.userId
     *
     * @param userId the value for xiwa_redstar_store_favorite.userId
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}