package com.lanchui.commonBiz.bean;

import com.lanchui.commonBiz.bean.constant.AvgScore;
import com.xiwa.base.bean.Identified;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RedstarStore implements Identified  {

    private int id;

    private String storeName;//   店铺名称

    private String storeType;//   店铺类型

    private String cityCode;//   所在城市code

    private String city;//   所在市

    private int belongMarketId;//   longyan商场Id

    private String belongMarketCode;//   longyan商场代码

    private String belongMarket;//   所属商场

    private Date openTime;//   营业时间start

    private Date closeTime;//   营业时间end

    private String openingTime;//   营业周期

    private String rootCategory;//   主营类目

    private String type;//   所属分类

    private String specialService;//   特色服务

    private String salesSupport;//   售后保障

    private String storeImg;//   店铺图片

    private String honors;//   荣誉资质

    private boolean fixedPrices;//   明码实价

    private boolean genuineQuery;//   正品查询

    private boolean greenLead;//   绿色领跑

    private boolean categorySales;//   分类热销

    private String brandLogo;//   品牌logo

    private String brandName;//   品牌名称

    private String introduction;//   品牌介绍

    private Date brandCreateDate;//   品牌创立时间

    private Date createDate;//   创建时间

    private String qrCode;//   二维码ID

    private String storeCode;//   龙果的商铺ID

    private boolean favorite;//   是否喜欢

    private String belongMarketAddress; //   龙眼商场地址

    private double score;//   数据、积分

    private String complaintTel;//   投诉电话

    public String getComplaintTel() {
        return complaintTel;
    }

    public void setComplaintTel(String complaintTel) {
        this.complaintTel = complaintTel;
    }

    private List<AvgScore> RedstarReviewDetail = new ArrayList();

    public List<AvgScore> getRedstarReviewDetail() {
        return RedstarReviewDetail;
    }

    public void setRedstarReviewDetail(List<AvgScore> redstarReviewDetail) {
        RedstarReviewDetail = redstarReviewDetail;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        DecimalFormat df=new DecimalFormat("#.00");
        this.score = Double.parseDouble(df.format(score));
    }

    public String getBelongMarketAddress() {
        return belongMarketAddress;
    }

    public void setBelongMarketAddress(String belongMarketAddress) {
        this.belongMarketAddress = belongMarketAddress;
    }

    public boolean getFavorite() {
        return favorite;
    }


    public void setFavorite(boolean favorite) {
        this.favorite = favorite;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.id
     *
     * @return the value of xiwa_redstar_store.id
     *
     * @mbggenerated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.id
     *
     * @param id the value for xiwa_redstar_store.id
     *
     * @mbggenerated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.storeName
     *
     * @return the value of xiwa_redstar_store.storeName
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.storeName
     *
     * @param storeName the value for xiwa_redstar_store.storeName
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.storeType
     *
     * @return the value of xiwa_redstar_store.storeType
     *
     * @mbggenerated
     */
    public String getStoreType() {
        return storeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.storeType
     *
     * @param storeType the value for xiwa_redstar_store.storeType
     *
     * @mbggenerated
     */
    public void setStoreType(String storeType) {
        this.storeType = storeType == null ? null : storeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.cityCode
     *
     * @return the value of xiwa_redstar_store.cityCode
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.cityCode
     *
     * @param cityCode the value for xiwa_redstar_store.cityCode
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.city
     *
     * @return the value of xiwa_redstar_store.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.city
     *
     * @param city the value for xiwa_redstar_store.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.belongMarketId
     *
     * @return the value of xiwa_redstar_store.belongMarketId
     *
     * @mbggenerated
     */
    public int getBelongMarketId() {
        return belongMarketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.belongMarketId
     *
     * @param belongMarketId the value for xiwa_redstar_store.belongMarketId
     *
     * @mbggenerated
     */
    public void setBelongMarketId(int belongMarketId) {
        this.belongMarketId = belongMarketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.belongMarketCode
     *
     * @return the value of xiwa_redstar_store.belongMarketCode
     *
     * @mbggenerated
     */
    public String getBelongMarketCode() {
        return belongMarketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.belongMarketCode
     *
     * @param belongMarketCode the value for xiwa_redstar_store.belongMarketCode
     *
     * @mbggenerated
     */
    public void setBelongMarketCode(String belongMarketCode) {
        this.belongMarketCode = belongMarketCode == null ? null : belongMarketCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.belongMarket
     *
     * @return the value of xiwa_redstar_store.belongMarket
     *
     * @mbggenerated
     */
    public String getBelongMarket() {
        return belongMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.belongMarket
     *
     * @param belongMarket the value for xiwa_redstar_store.belongMarket
     *
     * @mbggenerated
     */
    public void setBelongMarket(String belongMarket) {
        this.belongMarket = belongMarket == null ? null : belongMarket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.openTime
     *
     * @return the value of xiwa_redstar_store.openTime
     *
     * @mbggenerated
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.openTime
     *
     * @param openTime the value for xiwa_redstar_store.openTime
     *
     * @mbggenerated
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.closeTime
     *
     * @return the value of xiwa_redstar_store.closeTime
     *
     * @mbggenerated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.closeTime
     *
     * @param closeTime the value for xiwa_redstar_store.closeTime
     *
     * @mbggenerated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.openingTime
     *
     * @return the value of xiwa_redstar_store.openingTime
     *
     * @mbggenerated
     */
    public String getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.openingTime
     *
     * @param openingTime the value for xiwa_redstar_store.openingTime
     *
     * @mbggenerated
     */
    public void setOpeningTime(String openingTime) {
        this.openingTime = openingTime == null ? null : openingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.rootCategory
     *
     * @return the value of xiwa_redstar_store.rootCategory
     *
     * @mbggenerated
     */
    public String getRootCategory() {
        return rootCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.rootCategory
     *
     * @param rootCategory the value for xiwa_redstar_store.rootCategory
     *
     * @mbggenerated
     */
    public void setRootCategory(String rootCategory) {
        this.rootCategory = rootCategory == null ? null : rootCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.type
     *
     * @return the value of xiwa_redstar_store.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.type
     *
     * @param type the value for xiwa_redstar_store.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.specialService
     *
     * @return the value of xiwa_redstar_store.specialService
     *
     * @mbggenerated
     */
    public String getSpecialService() {
        return specialService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.specialService
     *
     * @param specialService the value for xiwa_redstar_store.specialService
     *
     * @mbggenerated
     */
    public void setSpecialService(String specialService) {
        this.specialService = specialService == null ? null : specialService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.salesSupport
     *
     * @return the value of xiwa_redstar_store.salesSupport
     *
     * @mbggenerated
     */
    public String getSalesSupport() {
        return salesSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.salesSupport
     *
     * @param salesSupport the value for xiwa_redstar_store.salesSupport
     *
     * @mbggenerated
     */
    public void setSalesSupport(String salesSupport) {
        this.salesSupport = salesSupport == null ? null : salesSupport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.storeImg
     *
     * @return the value of xiwa_redstar_store.storeImg
     *
     * @mbggenerated
     */
    public String getStoreImg() {
        return storeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.storeImg
     *
     * @param storeImg the value for xiwa_redstar_store.storeImg
     *
     * @mbggenerated
     */
    public void setStoreImg(String storeImg) {
        this.storeImg = storeImg == null ? null : storeImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.honors
     *
     * @return the value of xiwa_redstar_store.honors
     *
     * @mbggenerated
     */
    public String getHonors() {
        return honors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.honors
     *
     * @param honors the value for xiwa_redstar_store.honors
     *
     * @mbggenerated
     */
    public void setHonors(String honors) {
        this.honors = honors == null ? null : honors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.fixedPrices
     *
     * @return the value of xiwa_redstar_store.fixedPrices
     *
     * @mbggenerated
     */
    public boolean getFixedPrices() {
        return fixedPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.fixedPrices
     *
     * @param fixedPrices the value for xiwa_redstar_store.fixedPrices
     *
     * @mbggenerated
     */
    public void setFixedPrices(boolean fixedPrices) {
        this.fixedPrices = fixedPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.genuineQuery
     *
     * @return the value of xiwa_redstar_store.genuineQuery
     *
     * @mbggenerated
     */
    public boolean getGenuineQuery() {
        return genuineQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.genuineQuery
     *
     * @param genuineQuery the value for xiwa_redstar_store.genuineQuery
     *
     * @mbggenerated
     */
    public void setGenuineQuery(boolean genuineQuery) {
        this.genuineQuery = genuineQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.greenLead
     *
     * @return the value of xiwa_redstar_store.greenLead
     *
     * @mbggenerated
     */
    public boolean getGreenLead() {
        return greenLead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.greenLead
     *
     * @param greenLead the value for xiwa_redstar_store.greenLead
     *
     * @mbggenerated
     */
    public void setGreenLead(boolean greenLead) {
        this.greenLead = greenLead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.categorySales
     *
     * @return the value of xiwa_redstar_store.categorySales
     *
     * @mbggenerated
     */
    public boolean getCategorySales() {
        return categorySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.categorySales
     *
     * @param categorySales the value for xiwa_redstar_store.categorySales
     *
     * @mbggenerated
     */
    public void setCategorySales(boolean categorySales) {
        this.categorySales = categorySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.brandLogo
     *
     * @return the value of xiwa_redstar_store.brandLogo
     *
     * @mbggenerated
     */
    public String getBrandLogo() {
        return brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.brandLogo
     *
     * @param brandLogo the value for xiwa_redstar_store.brandLogo
     *
     * @mbggenerated
     */
    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo == null ? null : brandLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.brandName
     *
     * @return the value of xiwa_redstar_store.brandName
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.brandName
     *
     * @param brandName the value for xiwa_redstar_store.brandName
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.introduction
     *
     * @return the value of xiwa_redstar_store.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.introduction
     *
     * @param introduction the value for xiwa_redstar_store.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.brandCreateDate
     *
     * @return the value of xiwa_redstar_store.brandCreateDate
     *
     * @mbggenerated
     */
    public Date getBrandCreateDate() {
        return brandCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.brandCreateDate
     *
     * @param brandCreateDate the value for xiwa_redstar_store.brandCreateDate
     *
     * @mbggenerated
     */
    public void setBrandCreateDate(Date brandCreateDate) {
        this.brandCreateDate = brandCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.createDate
     *
     * @return the value of xiwa_redstar_store.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.createDate
     *
     * @param createDate the value for xiwa_redstar_store.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.qrCode
     *
     * @return the value of xiwa_redstar_store.qrCode
     *
     * @mbggenerated
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.qrCode
     *
     * @param qrCode the value for xiwa_redstar_store.qrCode
     *
     * @mbggenerated
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_store.stoveCode
     *
     * @return the value of xiwa_redstar_store.stoveCode
     *
     * @mbggenerated
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_store.stoveCode
     *
     * @param storeCode the value for xiwa_redstar_store.stoveCode
     *
     * @mbggenerated
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? "0" : storeCode.trim();
    }
}