package com.lanchui.commonBiz.bean;

import com.xiwa.base.bean.Identified;

import java.util.Date;

public class RedstarReviewLiked implements Identified {

    private int id;

    private int reviewId; //  点评Id

    private String userObject;

    private String userId;//  用户ID

    private Date createDate;//  创建ID

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_review_liked.id
     *
     * @return the value of xiwa_redstar_review_liked.id
     *
     * @mbggenerated
     */
    public int getId() {
        return id;
    }


    public void setId(int id) {
        this.id = id;
    }


    public int getReviewId() {
        return reviewId;
    }


    public void setReviewId(int reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_review_liked.userObject
     *
     * @return the value of xiwa_redstar_review_liked.userObject
     *
     * @mbggenerated
     */
    public String getUserObject() {
        return userObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_review_liked.userObject
     *
     * @param userObject the value for xiwa_redstar_review_liked.userObject
     *
     * @mbggenerated
     */
    public void setUserObject(String userObject) {
        this.userObject = userObject == null ? null : userObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_review_liked.userId
     *
     * @return the value of xiwa_redstar_review_liked.userId
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_review_liked.userId
     *
     * @param userId the value for xiwa_redstar_review_liked.userId
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiwa_redstar_review_liked.createDate
     *
     * @return the value of xiwa_redstar_review_liked.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiwa_redstar_review_liked.createDate
     *
     * @param createDate the value for xiwa_redstar_review_liked.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}