USE `bd_opp_api_app`;

INSERT INTO `xiwa_nvwa_component` (`id`, `name`, `alias`, `type`, `icon`)
VALUES
  (1, '文本框', 'text', 'field', 'align-justify'),
  (3, 'Label', 'label', 'text', 'pencil'),
  (4, '普通按钮', 'button', 'button', 'tasks'),
  (5, '多选框', 'checkbox', 'field', 'saved'),
  (6, '下拉选择框', 'combobox', 'text', 'sort-by-attributes'),
  (7, '隐藏域', 'hidden', 'text', 'credit-card'),
  (8, '图片', 'img', 'text', 'picture'),
  (9, '超链接', 'link', 'text', 'link'),
  (10, '单选框', 'radio', 'text', 'record'),
  (11, '下拉框', 'select', 'text', 'sort-by-attributes'),
  (12, '文本域', 'textarea', 'text', 'text-width'),
  (13, '富文本', 'umeditor', 'text', 'hdd');

INSERT INTO `xiwa_nvwa_custom_script` (`id`, `name`, `description`, `alias`, `code`, `type`)
VALUES
  (1, 'saveForm', '保存表单', 'saveForm',
   'define([\'js/util/http\',\'achy/widget/ui/message\',],function(http,Message) {\n    return {\n        execute: function(t) {\n          console.log(t);\n		  var formObjects=window.container[t.eleBean.containerBean.alias][\'elements\'];\n		  var pageAlias=\'preview\';\n		  var containerAlias=t.eleBean.containerBean.alias;\n		  var savePath=window.nvwaClientApi.createForm(pageAlias,containerAlias);\n		  var saveData={};\n		  $.each(formObjects,function(k,formObject){\n			if(formObject&&formObject.element.componentAlias&&formObject.getValue&&formObject.isValue()){\n			  	saveData[k]=formObject.getValue();\n			}	\n		  })\n		  var postData={};\n		  postData[\'form_list\']=JSON.stringify(saveData);\n		  http.request(savePath, postData, function(response) {\n                //返回的http请求数据\n                console.log(response);\n			if(response.ok){\n			  new Message({\n				type: \'info\',\n				msg: \'保存数据成功\',\n			  	timeout: 1500\n			  });\n			}else{\n			  new Message({\n				type: \'error\',\n				msg: \'保存数据失败\',\n			  	timeout: 1500\n			  });\n			}\n          }, false, \'POST\', false);\n		  \n		 // debugger;\n        }\n    };\n});',
   'javascript');

INSERT INTO `xiwa_nvwa_icon` (`name`, `alias`)
VALUES
  ('星号', 'asterisk'),
  ('加号', 'plus'),
  ('欧元', 'euro'),
  ('减号', 'minus'),
  ('云', 'cloud'),
  ('信封', 'envelope'),
  ('铅笔', 'pencil'),
  ('玻璃', 'glass'),
  ('音乐', 'music'),
  ('搜索', 'search'),
  ('爱心', 'heart'),
  ('星星', 'star'),
  ('空心爱心', 'heart-empty'),
  ('用户', 'user'),
  ('菲林', 'film'),
  ('大方块', 'th-large'),
  ('方块', 'th'),
  ('方块列表', 'th-list'),
  ('确认', 'ok'),
  ('删除', 'remove'),
  ('放大', 'zoom-in'),
  ('缩小', 'zoom-out'),
  ('关闭', 'off'),
  ('信号', 'signal'),
  ('齿轮', 'cog'),
  ('垃圾桶', 'trash'),
  ('首页', 'home'),
  ('文件', 'file'),
  ('时间', 'time'),
  ('公路', 'road'),
  ('下载全部', 'download-alt'),
  ('下载', 'download'),
  ('上传', 'upload'),
  ('盒子', 'inbox'),
  ('播放', 'play-circle'),
  ('循环', 'repeat'),
  ('刷新', 'refresh'),
  ('所有列表', 'list-alt'),
  ('锁定', 'lock'),
  ('红旗', 'flag'),
  ('耳机', 'headphones'),
  ('静音', 'volume-off'),
  ('减小音量', 'volume-down'),
  ('放大音量', 'volume-up'),
  ('二维码', 'qrcode'),
  ('条形码', 'barcode'),
  ('标签', 'tag'),
  ('很多标签', 'tags'),
  ('书', 'book'),
  ('书签', 'bookmark'),
  ('打印', 'print'),
  ('拍照', 'camera'),
  ('字体', 'font'),
  ('粗体', 'bold'),
  ('斜体', 'italic'),
  ('字体高度', 'text-height'),
  ('字体宽度', 'text-width'),
  ('左对齐', 'align-left'),
  ('居中', 'align-center'),
  ('右对齐', 'align-right'),
  ('两边对齐', 'align-justify'),
  ('列表', 'list'),
  ('向右缩进', 'indent-left'),
  ('向左缩进', 'indent-right'),
  ('视频', 'facetime-video'),
  ('图片', 'picture'),
  ('坐标', 'map-marker'),
  ('对比度', 'adjust'),
  ('水', 'tint'),
  ('编辑', 'edit'),
  ('分享', 'share'),
  ('检查', 'check'),
  ('移动', 'move'),
  ('上一步', 'step-backward'),
  ('快速回退', 'fast-backward'),
  ('回退', 'backward'),
  ('播放', 'play'),
  ('暂停', 'pause'),
  ('停止', 'stop'),
  ('前进', 'forward'),
  ('快进', 'fast-forward'),
  ('下一步', 'step-forward'),
  ('弹出', 'eject'),
  ('向左', 'chevron-left'),
  ('向右', 'chevron-right'),
  ('加号', 'plus-sign'),
  ('减号', 'minus-sign'),
  ('删除', 'remove-sign'),
  ('确认', 'ok-sign'),
  ('询问', 'question-sign'),
  ('信息', 'info-sign'),
  ('屏幕截图', 'screenshot'),
  ('删除', 'remove-circle'),
  ('确认', 'ok-circle'),
  ('禁用', 'ban-circle'),
  ('向左箭头', 'arrow-left'),
  ('向右箭头', 'arrow-right'),
  ('向上箭头', 'arrow-up'),
  ('向下箭头', 'arrow-down'),
  ('分享', 'share-alt'),
  ('最大尺寸', 'resize-full'),
  ('最小尺寸', 'resize-small'),
  ('信息', 'exclamation-sign'),
  ('礼物', 'gift'),
  ('叶子', 'leaf'),
  ('火', 'fire'),
  ('眼睛睁开', 'eye-open'),
  ('眼睛闭上', 'eye-close'),
  ('警告标志', 'warning-sign'),
  ('飞机', 'plane'),
  ('日历', 'calendar'),
  ('随机', 'random'),
  ('评论', 'comment'),
  ('磁铁', 'magnet'),
  ('向上', 'chevron-up'),
  ('向下', 'chevron-down'),
  ('转推', 'retweet'),
  ('购物车', 'shopping-cart'),
  ('关闭目录', 'folder-close'),
  ('打开目录', 'folder-open'),
  ('高度', 'resize-vertical'),
  ('宽度', 'resize-horizontal'),
  ('硬盘', 'hdd'),
  ('扬声器', 'bullhorn'),
  ('铃声', 'bell'),
  ('认证', 'certificate'),
  ('赞', 'thumbs-up'),
  ('踩', 'thumbs-down'),
  ('向右', 'hand-right'),
  ('向左', 'hand-left'),
  ('向上', 'hand-up'),
  ('向下', 'hand-down'),
  ('向右', 'circle-arrow-right'),
  ('向左', 'circle-arrow-left'),
  ('向上', 'circle-arrow-up'),
  ('向下', 'circle-arrow-down'),
  ('全球化', 'globe'),
  ('扳手', 'wrench'),
  ('任务', 'tasks'),
  ('过滤器', 'filter'),
  ('公文包', 'briefcase'),
  ('最大化', 'fullscreen'),
  ('仪表盘', 'dashboard'),
  ('别针', 'paperclip'),
  ('爱心', 'heart-empty'),
  ('链接', 'link'),
  ('手机', 'phone'),
  ('图钉', 'pushpin'),
  ('美元', 'usd'),
  ('法郎', 'gbp'),
  ('排序', 'sort'),
  ('降序', 'sort-by-alphabet'),
  ('升序', 'sort-by-alphabet-alt'),
  ('降序', 'sort-by-order'),
  ('升序', 'sort-by-order-alt'),
  ('升序', 'sort-by-attributes'),
  ('降序', 'sort-by-attributes-alt'),
  ('未选中', 'unchecked'),
  ('向左', 'expand'),
  ('向下', 'collapse-down'),
  ('向上', 'collapse-up'),
  ('登录', 'log-in'),
  ('刷新', 'flash'),
  ('登出', 'log-out'),
  ('新窗口', 'new-window'),
  ('记录', 'record'),
  ('保存', 'save'),
  ('打开', 'open'),
  ('已保存', 'saved'),
  ('导入', 'import'),
  ('导出', 'export'),
  ('发送', 'send'),
  ('软盘', 'floppy-disk'),
  ('存档', 'floppy-saved'),
  ('移除存档', 'floppy-remove'),
  ('已存档', 'floppy-save'),
  ('打开存档', 'floppy-open'),
  ('信用卡', 'credit-card'),
  ('传输', 'transfer'),
  ('餐具', 'cutlery'),
  ('头部', 'header'),
  ('比较', 'compressed'),
  ('听筒', 'earphone'),
  ('电话', 'phone-alt'),
  ('塔', 'tower'),
  ('状态', 'stats'),
  ('普通视频', 'sd-video'),
  ('高清视频', 'hd-video'),
  ('字幕', 'subtitles'),
  ('音响', 'sound-stereo'),
  ('杜比音效', 'sound-dolby'),
  ('5.1声道', 'sound-5-1'),
  ('6.1声道', 'sound-6-1'),
  ('7.1声道', 'sound-7-1'),
  ('版权', 'copyright-mark'),
  ('注册商标', 'registration-mark'),
  ('从云下载', 'cloud-download'),
  ('上传到云', 'cloud-upload'),
  ('树', 'tree-conifer'),
  ('树', 'tree-deciduous');
